version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
        prefix: 'deps'
    labels:
        - 'dependabot'
    target-branch: 'main'